CREATE TABLE IF NOT EXISTS gnomes (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    atribute VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS formulas (
    id SERIAL PRIMARY KEY,
    gnome_id INTEGER REFERENCES gnomes(id) ON DELETE CASCADE,
    descricao VARCHAR(100), 
    expressao TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);